Fixed a typo: replaced the version of cargo-size from 0.3.3 to 0.3.6
rust-embedded/discovery-mb2 pull request #13
Opened 2024-11-11 11:39 UTC by wubin28

2024-11-11 23:48 UTC, BartMassey requested changes
Thanks much! Better is probably

    cargo install cargo-binutils --vers '^0.3'

to keep it current as things change.

2024-11-12 05:48 UTC, wubin28 commented
Hi @BartMassey, I’ve updated the cargo-size version specification as suggested. Let me know if there’s anything else needed. Thanks for the feedback!

2024-11-13 04:25 UTC, wubin28 commented
The current documentation's ambiguity regarding the GDB command has caused significant confusion, particularly for newcomers to embedded Rust development. The text shows gdb in the command example, which can be misleading as this basic command often doesn't work for embedded development. In my own experience as a beginner, this led to a frustrating day-long debugging session, including reinstalling Ubuntu from 24.04 to 22.04, only to eventually discover that I needed to use gdb-multiarch instead of gdb on Ubuntu. A more helpful approach would be to provide explicit, OS-specific GDB commands in the note section, making it clear that Linux users need gdb-multiarch, while macOS and Windows users should use arm-none-eabi-gdb. This clarification would save other developers from similar time-consuming troubleshooting experiences.

2024-11-15 06:13 UTC, wubin28 commented
> The current documentation's ambiguity regarding the GDB command has caused significant confusion, particularly for newcomers to embedded Rust development. The text shows gdb in the command example, which can be misleading as this basic command often doesn't work for embedded development. In my own experience as a beginner, this led to a frustrating day-long debugging session, including reinstalling Ubuntu from 24.04 to 22.04, only to eventually discover that I needed to use gdb-multiarch instead of gdb on Ubuntu. A more helpful approach would be to provide explicit, OS-specific GDB commands in the note section, making it clear that Linux users need gdb-multiarch, while macOS and Windows users should use arm-none-eabi-gdb. This clarification would save other developers from similar time-consuming troubleshooting experiences.

I have removed commit `2393e6d` from this pull request as it was unrelated to the purpose of this PR. I may submit a separate PR for the changes introduced in `2393e6d` at a later time.

2025-03-21 00:49 UTC, merged

2025-03-21 00:49 UTC, BartMassey commented
@wubin28 Apologies for the long delay in merging this: I got a little confused about the status. Thanks much for the contribution.